Repository wecode-bootcamp-korea/21-1st-KaKa0Adult-frontend, pull requests merged in 2021-06, with the labels that each got.

#2 [21기 박현찬] Modify : login 리뷰 재반영
  package-lock.json
  public/data/loginData.json
  public/images/banner_login.png
  public/images/sprite.png
  public/index.html
  src/Pages/Login/Footer/index.js
  src/Pages/Login/Footer/index.scss
  src/Pages/Login/index.js
  src/Pages/Login/index.scss
  src/Styles/Common.scss
  src/Styles/reset.scss
  src/config.js
  src/utils/fetches.js
  src/utils/regex.js
Labels: Status: 리뷰 요청

#4 [21기 이상훈] Add: 리뷰 사항 정리(early 리턴 및 오탈자, 구조분해 할당)
  public/images/basketIcon.png
  public/images/chracterIcon.png
  public/images/deleteX.png
  public/images/emptyImg.png
  public/images/hamburgerIcon.png
  public/images/icon_checked.png
  public/images/icon_checked_ok.png
  public/images/icon_search_remove.png
  public/images/logo.png
  public/images/search.png
  public/images/search_main.png
  public/images/thumb.jpeg
  public/images/trashcan-btn.png
  src/Components/Aside/index.js
  src/Components/Footer/index.js
  src/Components/Nav/Searchbar/CategoryView/index.js
  src/Components/Nav/Searchbar/ResultView/index.js
  src/Components/Nav/Searchbar/index.js
  src/Components/Nav/index.js
  src/Components/Nav/index.scss
  src/Data/categoryData.js
  src/Data/characterData.js
  src/Pages/Main/index.js
  src/Pages/Main/index.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#7 [21기 이상훈] Add: footer 레이아웃 및 CSS, 토글기능 구현
  public/images/arrow-footer-close.png
  public/images/arrow-footer-open.png
  src/Components/Footer/index.js
  src/Components/Footer/index.scss
  src/Pages/Main/index.js
Labels: Status: Accepted

#12 [21기 박현찬] Refactoring : fetch header 리펙토링
  src/utils/fetches.js
  src/utils/queryString.js
  src/utils/storage.js
Labels: Status: Accepted

#8 [21기 이상훈] Add: 동적 메뉴 변화 및 컨포넌트 변화 적용, 리뷰 반영
  src/Components/Carousel/index.js
  src/Pages/Main/Components/MainTab/index.js
  src/Pages/Main/Components/MainTab/index.scss
  src/Pages/Main/HotProducts/index.js
  src/Pages/Main/MyPage/index.js
  src/Pages/Main/NewProducts/index.js
  src/Pages/Main/index.js
  src/Pages/Main/index.scss
  src/utils/fetches.js
  src/utils/storage.js
Labels: Status: 리뷰 요청

#9 [21기 이상훈] Add: 캐러셀 상수 분리 및 컨벤션 정리
  public/data/carouselData.json
  public/images/arrow-left.png
  public/images/arrow-right.png
  public/images/carousel_1.jpeg
  public/images/carousel_2.jpeg
  src/Components/Carousel/CarouselFrame/index.js
  src/Components/Carousel/CarouselFrame/index.scss
  src/Components/Carousel/CarouselList/index.js
  src/Components/Carousel/index.scss
  src/Pages/Main/index.js
Labels: Status: 리뷰 요청

#10 [21기 박현찬] Modify : 리뷰 반영, 로그인 로그아웃 라우팅 기능 추가
  public/images/PetCharacter.png
  public/images/addToCart.png
  public/images/addToLike.png
  public/images/alert-bell.jpg
  public/images/cart.png
  public/images/category_toy_M_201113.jpg
  public/images/checkIcon.png
  public/images/checkOkIcon.png
  public/images/colorcheck.png
  public/images/dropdown.png
  public/images/empty-heart.png
  public/images/gnb-home-18-black@2x.png
  public/images/heart.png
  public/images/heartRed.png
  public/images/ico_category_header_fold.png
  public/images/ico_top.png
  public/images/language-global-18-black@2x.png
  public/images/logo-footer-commerce.png
  public/images/product.jpg
  public/images/smallDropdown.png
  public/images/soldout.png
  src/Components/Aside/index.js
  src/Components/Aside/index.scss
  src/Components/AsideMenu/Accordion/index.js
  src/Components/AsideMenu/Accordion/index.scss
  src/Components/AsideMenu/Menu/index.js
  src/Components/AsideMenu/Menu/index.scss
  src/Components/AsideMenu/index.js
  src/Components/AsideMenu/index.scss
  src/Components/Nav/index.js
  src/Data/characterData.js
  src/Pages/Signup/index.js
Labels: Status: 리뷰 요청

#11 [21기 박현찬] Merge : 충돌 해결
  src/Components/Product/index.js
  src/Components/Product/index.scss
  src/Components/ProductList/index.js
  src/Components/ProductList/index.scss
  src/Components/ProductList/newProductData.js
  src/Pages/Character/FilterModal/index.js
  src/Pages/Character/index.js
  src/Pages/Character/index.scss
  src/Pages/Detail/index.js
  src/Pages/Detail/index.scss
  src/Pages/Signup/index.js
  src/Routes.js
Labels: Status: Accepted

#13 [21기 이상훈] 장바구니 충돌 수정 및 리뷰 반영 데이터 연동 및 뷰 영역 구현 함수 보완
  public/data/cartdata.json
  public/index.html
  src/Pages/Main/MyPage/Cart/CartList/index.js
  src/Pages/Main/MyPage/Cart/index.js
  src/Pages/Main/MyPage/Cart/index.scss
  src/Pages/Main/MyPage/index.js
  src/Pages/Signup/index.js
  src/config.js
Labels: Status: 수정 요청

#15 [21기 이상훈] 함수 연결 및 오탈자 수정
  public/data/orderData.json
  public/index.html
  src/Pages/Main/MyPage/index.js
  src/Pages/Main/Order/OrderList/index.js
  src/Pages/Main/Order/OrderList/index.scss
  src/Pages/Main/Order/OrderPrice/index.js
  src/Pages/Main/Order/OrderPrice/index.scss
  src/Pages/Main/Order/index.js
  src/Pages/Main/Order/index.scss
  src/Pages/Main/index.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#16 [21기 박현찬] Add : 상세 페이지 완료
  public/index.html
  src/Pages/Detail/index.js
  src/Pages/Detail/index.scss
Labels: Status: 리뷰 요청

#17 [21기 박현찬] Add : to last merge
  src/Components/Carousel/index.scss
  src/Components/ProductList/index.js
  src/Components/ProductList/index.scss
  src/Pages/Detail/CarouseList/index.js
  src/Pages/Detail/CarouselFrame/index.js
  src/Pages/Detail/CarouselFrame/index.scss
  src/Pages/Main/HotProducts/GridCard/index.js
  src/Pages/Main/HotProducts/GridCard/index.scss
  src/Pages/Main/HotProducts/hotData.js
  src/Pages/Main/HotProducts/index.js
  src/Pages/Main/HotProducts/index.scss
  src/Pages/Main/MyPage/Cart/Order/OrderList/index.js
  src/Pages/Main/MyPage/Cart/Order/OrderList/index.scss
  src/Pages/Main/MyPage/Cart/Order/OrderPrice/index.js
  src/Pages/Main/MyPage/Cart/Order/OrderPrice/index.scss
  src/Pages/Main/MyPage/Cart/Order/index.js
  src/Pages/Main/MyPage/Cart/Order/index.scss
  src/Pages/Main/MyPage/Cart/index.js
  src/Pages/Main/MyPage/Components/SubTab/index.js
  src/Pages/Main/MyPage/Components/SubTab/index.scss
  src/Pages/Main/MyPage/index.js
  src/Pages/Main/NewProducts/index.js
  src/Pages/Main/NewProducts/index.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#18 [21기 이상훈] add: 오더 수정
  src/Pages/Main/MyPage/Cart/Order/index.js
  src/Pages/Main/MyPage/Cart/index.js
  src/config.js
  src/utils/fetches.js
Labels: Status: 리뷰 요청
